# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Download(object):
    def setupUi(self, Download):
        Download.setObjectName("Download")
        Download.resize(368, 176)
        Download.setMinimumSize(QtCore.QSize(368, 176))
        Download.setMaximumSize(QtCore.QSize(368, 176))
        self.videoTitleLabel = QtWidgets.QLabel(Download)
        self.videoTitleLabel.setGeometry(QtCore.QRect(10, 10, 351, 16))
        self.videoTitleLabel.setTextFormat(QtCore.Qt.PlainText)
        self.videoTitleLabel.setScaledContents(False)
        self.videoTitleLabel.setObjectName("videoTitleLabel")
        self.authorLabel = QtWidgets.QLabel(Download)
        self.authorLabel.setGeometry(QtCore.QRect(10, 30, 351, 16))
        self.authorLabel.setObjectName("authorLabel")
        self.downloadButton = QtWidgets.QPushButton(Download)
        self.downloadButton.setGeometry(QtCore.QRect(280, 140, 75, 23))
        self.downloadButton.setObjectName("downloadButton")
        self.lineEdit = QtWidgets.QLineEdit(Download)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(92, 141, 181, 20))
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.browseButton = QtWidgets.QPushButton(Download)
        self.browseButton.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.browseButton.setObjectName("browseButton")
        self.resolutionLabel = QtWidgets.QLabel(Download)
        self.resolutionLabel.setGeometry(QtCore.QRect(10, 60, 351, 16))
        self.resolutionLabel.setObjectName("resolutionLabel")
        self.fpsLabel = QtWidgets.QLabel(Download)
        self.fpsLabel.setGeometry(QtCore.QRect(10, 80, 351, 16))
        self.fpsLabel.setObjectName("fpsLabel")
        self.loadingBar = QtWidgets.QProgressBar(Download)
        self.loadingBar.setGeometry(QtCore.QRect(10, 110, 351, 20))
        self.loadingBar.setProperty("value", 0)
        self.loadingBar.setTextVisible(True)
        self.loadingBar.setInvertedAppearance(False)
        self.loadingBar.setObjectName("loadingBar")

        self.retranslateUi(Download)
        QtCore.QMetaObject.connectSlotsByName(Download)

    def retranslateUi(self, Download):
        _translate = QtCore.QCoreApplication.translate
        Download.setWindowTitle(_translate("Download", "Dialog"))
        self.videoTitleLabel.setText(_translate("Download", "Video title"))
        self.authorLabel.setText(_translate("Download", "Author"))
        self.downloadButton.setText(_translate("Download", "Download"))
        self.browseButton.setText(_translate("Download", "Browse"))
        self.resolutionLabel.setText(_translate("Download", "Resolution"))
        self.fpsLabel.setText(_translate("Download", "FPS"))
