# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ADV(object):
    def setupUi(self, ADV):
        ADV.setObjectName("ADV")
        ADV.resize(400, 301)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ADV.sizePolicy().hasHeightForWidth())
        ADV.setSizePolicy(sizePolicy)
        ADV.setMinimumSize(QtCore.QSize(400, 300))
        self.centralwidget = QtWidgets.QWidget(ADV)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pasteLinkButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasteLinkButton.sizePolicy().hasHeightForWidth())
        self.pasteLinkButton.setSizePolicy(sizePolicy)
        self.pasteLinkButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pasteLinkButton.setDefault(False)
        self.pasteLinkButton.setFlat(False)
        self.pasteLinkButton.setObjectName("pasteLinkButton")
        self.verticalLayout.addWidget(self.pasteLinkButton)
        self.linkText = QtWidgets.QLabel(self.centralwidget)
        self.linkText.setText("")
        self.linkText.setObjectName("linkText")
        self.verticalLayout.addWidget(self.linkText)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(1)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 165))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_layout = QtWidgets.QVBoxLayout()
        self.widget_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.widget_layout.setSpacing(0)
        self.widget_layout.setObjectName("widget_layout")
        self.horizontalLayout.addLayout(self.widget_layout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        ADV.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ADV)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        ADV.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ADV)
        self.statusbar.setObjectName("statusbar")
        ADV.setStatusBar(self.statusbar)

        self.retranslateUi(ADV)
        QtCore.QMetaObject.connectSlotsByName(ADV)

    def retranslateUi(self, ADV):
        _translate = QtCore.QCoreApplication.translate
        ADV.setWindowTitle(_translate("ADV", "ADV Video Downloader"))
        self.pasteLinkButton.setText(_translate("ADV", "Paste link"))
